// Mad Libs-style random prompt generator for the "Surprise Me" button on the
// CLAWD PFP Generator. The goal is playful, creative, PG-ish combinations.
// Keeping arrays here (instead of inline in the component) keeps the form
// component readable and makes the word banks easy to extend.

const ADJECTIVES = [
  "grumpy",
  "majestic",
  "disheveled",
  "suspicious",
  "radiant",
  "existential",
  "overconfident",
  "world-weary",
  "caffeinated",
  "enlightened",
  "bewildered",
  "dapper",
  "sleep-deprived",
  "philosophical",
  "triumphant",
  "heartbroken",
  "scheming",
  "zen",
  "melancholy",
  "mischievous",
  "stoic",
  "flustered",
  "glamorous",
  "paranoid",
  "smug",
  "brooding",
  "whimsical",
  "regal",
  "bashful",
  "exasperated",
  "jaded",
  "smoldering",
  "pompous",
  "giddy",
  "perplexed",
  "nonchalant",
  "ruthless",
  "unflappable",
  "wistful",
  "haughty",
  "sheepish",
  "smitten",
  "indignant",
  "feral",
  "pensive",
  "audacious",
  "hangry",
  "euphoric",
  "delirious",
  "unbothered",
  "cocky",
  "flabbergasted",
  "contemplative",
  "unhinged",
  "snooty",
  "beleaguered",
  "nefarious",
  "jovial",
  "spellbound",
  "swaggering",
  "shellshocked",
  "introspective",
  "vainglorious",
  "woebegone",
  "resolute",
  "incandescent",
  "flamboyant",
  "imperious",
  "tormented",
  "enigmatic",
  "devious",
  "hangdog",
  "starstruck",
  "beatific",
  "conspiratorial",
  "indefatigable",
  "jubilant",
  "mortified",
  "pious",
  "ravenous",
  "wide-eyed",
  "aloof",
  "combative",
  "earnest",
  "frazzled",
  "hypnotic",
  "impish",
  "nostalgic",
  "rakish",
  "tranquil",
  "vengeful",
];

const SUBJECTS = [
  "accountant",
  "pirate captain",
  "yoga instructor",
  "detective",
  "astronaut",
  "barista",
  "librarian",
  "carnival barker",
  "wizard",
  "stand-up comedian",
  "chess grandmaster",
  "lighthouse keeper",
  "jazz trumpeter",
  "sushi chef",
  "motivational speaker",
  "fortune teller",
  "park ranger",
  "opera singer",
  "ice cream vendor",
  "bounty hunter",
  "tango dancer",
  "rodeo clown",
  "samurai",
  "DJ",
  "tax auditor",
  "cryptozoologist",
  "mime",
  "blacksmith",
  "cartographer",
  "beekeeper",
  "food critic",
  "life coach",
  "theater critic",
  "tarot reader",
  "puppeteer",
  "zamboni driver",
  "auctioneer",
  "sommelier",
  "lumberjack",
  "cowboy",
  "air traffic controller",
  "goat herder",
  "mail carrier",
  "elevator operator",
  "gondolier",
  "falconer",
  "private investigator",
  "bassoonist",
  "locksmith",
  "cheesemonger",
  "kombucha brewer",
  "ghost hunter",
  "ventriloquist",
  "ballet dancer",
  "kayak instructor",
  "hot dog vendor",
  "train conductor",
  "mushroom forager",
  "mountaineer",
  "alchemist",
  "court jester",
  "Viking raider",
  "poker dealer",
  "tattoo artist",
  "pastry chef",
  "escape artist",
  "Renaissance fair knight",
  "crystal healer",
  "fire juggler",
  "taxidermist",
  "subway conductor",
  "balloon artist",
  "wedding photographer",
  "dog walker",
  "tech bro",
  "used-car salesman",
  "telemarketer",
  "customs agent",
  "sleep consultant",
  "professional wrestler",
  "orchestra conductor",
  "underwater welder",
  "surfing instructor",
  "mortician",
  "mall security guard",
  "hot sauce sommelier",
  "vintage typewriter repairman",
  "notary public",
  "insurance adjuster",
  "cave diver",
  "UFO researcher",
  "jet ski instructor",
  "knight errant",
  "river boat captain",
  "olympic curler",
  "glassblower",
  "archivist",
  "dog psychologist",
  "truffle hunter",
  "artisanal mayonnaise maker",
  "midnight security guard",
  "hot air balloon pilot",
  "luchador",
  "fiddle player",
  "weekend DJ",
  "tour guide",
  "ice sculptor",
  "scarecrow",
  "flamenco dancer",
  "birdwatcher",
  "stage magician",
  "paleontologist",
  "cult leader in recovery",
  "door-to-door encyclopedia salesman",
];

const SETTINGS = [
  "at a craps table",
  "in a thunderstorm",
  "on a rooftop at sunset",
  "at a karaoke bar",
  "in a submarine",
  "at a farmer's market",
  "in a lighthouse",
  "at a haunted motel",
  "in a space diner",
  "on a paddleboard",
  "on the Oregon Trail",
  "in a 24-hour laundromat",
  "at the county fair",
  "in a misty bamboo forest",
  "on a cruise ship buffet",
  "at a roadside taco stand",
  "in an abandoned arcade",
  "on the summit of a volcano",
  "at a silent disco",
  "in a Tokyo vending machine alley",
  "at a drive-in movie",
  "in a snow globe",
  "at a Las Vegas wedding chapel",
  "on a trans-Siberian train",
  "in a Parisian cafe at dawn",
  "at a roller rink",
  "on a dirigible",
  "at a ski lodge fireplace",
  "in a greenhouse",
  "on a pirate ship in the fog",
  "at a 1990s mall food court",
  "in a moonlit temple",
  "on the back of a giant turtle",
  "in a crystal cavern",
  "at a monster truck rally",
  "on a Venetian gondola",
  "at an underground speakeasy",
  "in a giant pumpkin patch",
  "on an ice floe with penguins",
  "at a Monte Carlo casino",
  "in a wildflower meadow",
  "at a desert oasis",
  "on a rollercoaster at night",
  "in a kaleidoscope",
  "at an ancient observatory",
  "on a tropical beach at dusk",
  "in a medieval tavern",
  "at a corner store at 3 AM",
  "on a suspension bridge in the mist",
  "in a redwood grove",
  "at a cherry blossom festival",
  "on the deck of a hot air balloon",
  "in an ice palace",
  "at a Mongolian steppe campfire",
  "on a flying carpet",
  "in a steampunk workshop",
  "at an abandoned train station",
  "on the moon",
  "in a tulip field",
  "at a tiki bar",
  "on a sailboat during a squall",
  "in the Library of Alexandria",
  "at a rainy Seattle bus stop",
  "on a ferry to nowhere",
  "in a treehouse",
  "at a carnival at midnight",
  "on the Great Wall of China",
  "in a Victorian greenhouse",
  "at a punk rock show",
  "on the tarmac of a private airport",
  "in a cathedral",
  "at a psychic fair",
  "on a zeppelin over Manhattan",
  "in a bioluminescent cave",
  "at a haunted diner",
  "on a Ferris wheel",
  "in an Escher-style staircase",
  "at a vintage toy store",
  "on a coral reef",
  "at an ancient Roman bath",
  "in a foggy moor",
  "at a dive bar jukebox",
  "on a boardwalk in the rain",
  "in a moonlit bowling alley",
  "at a chess tournament in the park",
  "in a sprawling art studio",
  "at a record store crate-dig",
  "on a Tokyo crosswalk in the rain",
  "in a frost-covered cottage",
  "at a rooftop pool at sunrise",
  "in a jazz club basement",
  "on the Orient Express",
  "at a midnight poker game",
];

const STYLES = [
  "renaissance painting",
  "comic book style",
  "oil painting",
  "claymation",
  "neon cyberpunk",
  "watercolor",
  "pixel art",
  "film noir",
  "ukiyo-e woodblock print",
  "low-poly 3D render",
  "stained glass",
  "chalk pastel",
  "vaporwave",
  "art deco poster",
  "storybook illustration",
  "polaroid photograph",
  "charcoal sketch",
  "risograph print",
  "mosaic tile",
  "copper etching",
  "gouache painting",
  "gothic tapestry",
  "graffiti mural",
  "linocut print",
  "Art Nouveau poster",
  "Bauhaus geometric",
  "surrealist dreamscape",
  "impressionist brushwork",
  "pop art silkscreen",
  "pencil sketch",
  "vintage pulp magazine cover",
  "Studio Ghibli anime",
  "1980s fantasy movie poster",
  "Saul Bass minimal",
  "Victorian engraving",
  "baroque masterpiece",
  "pointillism",
  "Byzantine icon",
  "blueprint schematic",
  "fresco",
  "cel-shaded cartoon",
  "1990s Nickelodeon style",
  "bas-relief sculpture",
  "pressed-flower art",
  "cross-stitch embroidery",
  "scratchboard",
  "cyanotype photogram",
  "tilt-shift miniature",
  "8-bit retro video game",
  "papercraft diorama",
  "glitch art",
  "Mughal miniature",
  "Rococo portrait",
  "comics newsprint",
  "Pixar 3D render",
  "sumi-e ink wash",
  "vintage Atari box art",
  "x-ray photograph",
  "technicolor musical still",
  "mid-century modern illustration",
  "soft pastel airbrush",
  "woodcut block print",
  "noir pulp paperback",
  "lo-fi anime",
  "sticker sheet vector",
  "trading card foil",
  "risky crayon on cardboard",
];

function pick<T>(arr: readonly T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

export const MAX_SURPRISE_PROMPT_LENGTH = 280;

export function getRandomSurprisePrompt(maxLength = MAX_SURPRISE_PROMPT_LENGTH): string {
  for (let i = 0; i < 5; i++) {
    const adj = pick(ADJECTIVES);
    const subject = pick(SUBJECTS);
    const setting = pick(SETTINGS);
    const style = pick(STYLES);
    const prompt = `${adj} ${subject} ${setting}, art style: ${style}`;
    if (prompt.length <= maxLength) return prompt;
  }
  return `${pick(ADJECTIVES)} ${pick(SUBJECTS)}`;
}
